@startuml
[Stereotypes] <<..annotations..>>
[Controller] <<..controllers..>>
[Persistence] <<..repository..>>
[Service] <<..service..>>

[Controller] --> [Stereotypes]
[Persistence] --> [Stereotypes]
[Controller] --> [Service]
[Service] --> [Persistence]

@enduml